/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedStationsIndexRouteImport } from './routes/_authenticated/stations/index'
import { Route as AuthenticatedStationsCreateRouteImport } from './routes/_authenticated/stations/create'
import { Route as AuthenticatedStationsStationIdIndexRouteImport } from './routes/_authenticated/stations/$stationId/index'
import { Route as AuthenticatedStationsStationIdEditRouteImport } from './routes/_authenticated/stations/$stationId/edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStationsIndexRoute =
  AuthenticatedStationsIndexRouteImport.update({
    id: '/stations/',
    path: '/stations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStationsCreateRoute =
  AuthenticatedStationsCreateRouteImport.update({
    id: '/stations/create',
    path: '/stations/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStationsStationIdIndexRoute =
  AuthenticatedStationsStationIdIndexRouteImport.update({
    id: '/stations/$stationId/',
    path: '/stations/$stationId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStationsStationIdEditRoute =
  AuthenticatedStationsStationIdEditRouteImport.update({
    id: '/stations/$stationId/edit',
    path: '/stations/$stationId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/stations/create': typeof AuthenticatedStationsCreateRoute
  '/stations': typeof AuthenticatedStationsIndexRoute
  '/stations/$stationId/edit': typeof AuthenticatedStationsStationIdEditRoute
  '/stations/$stationId': typeof AuthenticatedStationsStationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/stations/create': typeof AuthenticatedStationsCreateRoute
  '/stations': typeof AuthenticatedStationsIndexRoute
  '/stations/$stationId/edit': typeof AuthenticatedStationsStationIdEditRoute
  '/stations/$stationId': typeof AuthenticatedStationsStationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/_authenticated/stations/create': typeof AuthenticatedStationsCreateRoute
  '/_authenticated/stations/': typeof AuthenticatedStationsIndexRoute
  '/_authenticated/stations/$stationId/edit': typeof AuthenticatedStationsStationIdEditRoute
  '/_authenticated/stations/$stationId/': typeof AuthenticatedStationsStationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/dashboard'
    | '/settings'
    | '/login'
    | '/register'
    | '/stations/create'
    | '/stations'
    | '/stations/$stationId/edit'
    | '/stations/$stationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/dashboard'
    | '/settings'
    | '/login'
    | '/register'
    | '/stations/create'
    | '/stations'
    | '/stations/$stationId/edit'
    | '/stations/$stationId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/bookings'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/login/'
    | '/register/'
    | '/_authenticated/stations/create'
    | '/_authenticated/stations/'
    | '/_authenticated/stations/$stationId/edit'
    | '/_authenticated/stations/$stationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stations/': {
      id: '/_authenticated/stations/'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof AuthenticatedStationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stations/create': {
      id: '/_authenticated/stations/create'
      path: '/stations/create'
      fullPath: '/stations/create'
      preLoaderRoute: typeof AuthenticatedStationsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stations/$stationId/': {
      id: '/_authenticated/stations/$stationId/'
      path: '/stations/$stationId'
      fullPath: '/stations/$stationId'
      preLoaderRoute: typeof AuthenticatedStationsStationIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stations/$stationId/edit': {
      id: '/_authenticated/stations/$stationId/edit'
      path: '/stations/$stationId/edit'
      fullPath: '/stations/$stationId/edit'
      preLoaderRoute: typeof AuthenticatedStationsStationIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStationsCreateRoute: typeof AuthenticatedStationsCreateRoute
  AuthenticatedStationsIndexRoute: typeof AuthenticatedStationsIndexRoute
  AuthenticatedStationsStationIdEditRoute: typeof AuthenticatedStationsStationIdEditRoute
  AuthenticatedStationsStationIdIndexRoute: typeof AuthenticatedStationsStationIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStationsCreateRoute: AuthenticatedStationsCreateRoute,
  AuthenticatedStationsIndexRoute: AuthenticatedStationsIndexRoute,
  AuthenticatedStationsStationIdEditRoute:
    AuthenticatedStationsStationIdEditRoute,
  AuthenticatedStationsStationIdIndexRoute:
    AuthenticatedStationsStationIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
